---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: movy-app
  namespace: movy-test
spec:
  interval: 1m0s
  ref:
    branch: movy-test
  url: https://github.com/Musk8teers/container.training-spring-music/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: movy
  namespace: movy-test
spec:
  interval: 1m0s
  path: ./k8s
  prune: false
  serviceAccountName: movy
  sourceRef:
    kind: GitRepository
    name: movy-app
