apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Remember to update this if you use this manifest to obtain real certificates :)
    email: ludovic.piot@thegaragebandofit.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # To use the production environment, use the following line instead:
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: highfive-cert
  namespace: default
spec:
  commonName: enix.thegaragebandofit.com
  secretName: highfive-cert
  dnsNames:
    - enix.thegaragebandofit.com
    - grafana.enix.thegaragebandofit.com
    - blue.enix.thegaragebandofit.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
