apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: cluster-example
    namespace: cnpg-system
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: cluster-example
    podMetricsEndpoints:
        - port: metrics
