apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: olm
    namespace: olm
spec:
    interval: 1m0s
    ref:
        tag: v0.40.0
    url: https://github.com/operator-framework/operator-lifecycle-manager/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: olm
    namespace: olm
spec:
    interval: 1m0s
    path: ./deploy/upstream/quickstart/
    prune: false
    sourceRef:
        kind: GitRepository
        name: olm
