apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - sync.yaml
configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
