---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rocky-app
  namespace: rocky-test
spec:
  interval: 1m0s
  ref:
    branch: rocky-test
  url: https://github.com/Musk8teers/container.training-spring-music/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rocky
  namespace: rocky-test
spec:
  interval: 1m0s
  path: ./k8s
  prune: false
  serviceAccountName: rocky
  sourceRef:
    kind: GitRepository
    name: rocky-app
